platform :ios, '9.0'

target 'chatTestProject' do
    use_frameworks!

    pod 'Firebase/Core'
    pod 'Firebase/Storage'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'MessageKit'

end
